Roasts-and-Rants/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Roasts_and_Rants.Models {

	/// <summary>
	/// Represents a restaurant
	/// Holds a reference to Address
	/// Has a many-to-many relationship with User
	///    Association class: Review
	///    Has a one-to-many relationship with Review
	/// 
	/// Has a one-to-one relationship with Address
	/// </summary>
	public class Restaurant {

		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		[ScaffoldColumn(false)]
		public int RestaurantID { get; set; }

		[Required]
		[StringLength(50, ErrorMessage = "Restaurant Name should be within 50 characters")]
		public string Name { get; set; }

		[Display(Name = "Phone Number")]
		[DataType(DataType.PhoneNumber)]
		[RegularExpression(@"^\D?(\d{3})\D?\D?(\d{3})\D?(\d{4})$", ErrorMessage = "Please enter the phone number in a valid format")]
		public string Phone { get; set; }

		/// <summary>
		/// Reference to the Address of a restaurant
		/// </summary>
		//public virtual Address Address { get; set; }

		public string Street { get; set; }
		public string City { get; set; }
		public string State { get; set; }
		public string Country { get; set; }

		[DataType(DataType.PostalCode)]
		[RegularExpression(@"^(?!0+$)[0-9]{5,5}$", ErrorMessage = "Please enter a valid zip code")]
		[Display(Name = "Zip code")]
		public string PostalCode { get; set; }

		/// <summary>
		/// Custom display method for a Restaurant's Address
		/// 
		/// 1234 Example St
		/// Reston, VA, USA 20170
		/// </summary>
		/// <returns></returns>
		public string DisplayAddress() {
			return Street + "<br />" + City + ", " + State + ", " + Country + PostalCode;
		}

		/// <summary>
		/// Represents the one-to-many relationship between Restaurant and Review
		/// </summary>
		public virtual List<Review> Reviews { get; set; }

		/// <summary>
		/// Computed column
		/// </summary>
		[NotMapped]
		[Display(Name = "Average Rating")]
		public decimal AverageRating { get; set; }
	}
}

Roasts-and-Rants/Models/Review.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Roasts_and_Rants.Models {

	/// <summary>
	/// Represents a User Review for a Restaurant
	/// Association class for User and Review
	/// </summary>
	public class Review {

		/// <summary>
		/// Auto-incrementing field in the database
		/// Serves as the primary key
		/// </summary>
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int ReviewID { get; set; }

		/// <summary>
		/// Holds the rating the user gives a restaurant
		/// Should be limited to a range 1-10
		/// </summary>
		private const string error_message = "Please give a rating from 1.00 to 10.00";
		[Required(ErrorMessage = error_message)]
		[Range(1.00, 10.00)]
		[RegularExpression(@"^[0-9]{1,2}(.[0-9]{1,2})?$", ErrorMessage = "Please enter a valid rating.")]
		public decimal Rating { get; set; }

		/// <summary>
		/// Holds the comments that a user has about a restaurant
		/// </summary>
		[StringLength(500)]
		public string Content { get; set; }

		[DataType(DataType.Date)]
		[DisplayFormat(DataFormatString = "{0:mm-dd-yyyy}")]
		public DateTime ModifiedDate { get; set; }

		/// <summary>
		/// Reference to Restaurant
		/// </summary>
		[ForeignKey("Restaurant")]
		public int RestaurantID { get; set; }
		public virtual Restaurant Restaurant { get; set; }

		/// <summary>
		/// Reference to the user that created the review
		/// </summary>
		public string UserID { get; set; }
		public string UserName { get; set; }
	}
}

Roasts-and-Rants/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Roasts_and_Rants.DAL;
using Roasts_and_Rants.Models;

namespace Roasts_and_Rants.Controllers {

	public class RestaurantController : Controller {

		private RestaurantReviewContext db = new RestaurantReviewContext();

		// GET: Restaurant
		public ActionResult Index(string sortOrder, string searchString) {

			// Calculate the average of the ratings of each restaurant
			foreach (Restaurant rest in db.Restaurants) {
				if (rest.Reviews.Count > 0) {
					rest.AverageRating = CalculateAverageRating(rest);
				}
			}

			// Decide sort order
			ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			ViewBag.RatingSortParam = sortOrder == "rating" ? "rating_desc" : "rating";
			var restaurants = from r in db.Restaurants
							  select r;

			// Check to see if the Name, Phone, or Address fields contains the search string
			if (!String.IsNullOrEmpty(searchString)) {
				restaurants = restaurants.Where(r => r.Name.Contains(searchString)
					|| r.Phone.Contains(searchString) || r.Street.Contains(searchString)
					|| r.State.Contains(searchString)  || r.City.Contains(searchString)
					|| r.Country.Contains(searchString) || r.PostalCode.Contains(searchString));
			}

			// Decide how the list should be ordered
			IEnumerable<Restaurant> orderedRestaurants;
			switch (sortOrder) {
				case "name_desc":
					orderedRestaurants = restaurants.OrderByDescending(rest => rest.Name);
					break;
				case "rating":
					orderedRestaurants = restaurants.ToList().OrderBy(rest => rest.AverageRating);
					break;
				case "rating_desc":
					orderedRestaurants = restaurants.ToList().OrderByDescending(rest => rest.AverageRating);
					break;
				default:
					orderedRestaurants = restaurants.OrderBy(rest => rest.Name);
					break;
			}

			return View(orderedRestaurants.ToList());
		}

		// Helper method to calculate the Average rating of a restaurant
		private decimal CalculateAverageRating(Restaurant restaurant) {
			return restaurant.Reviews.Average(r => r.Rating);
		}

		// Not in use
		// Redirect to Reviews
		public ActionResult Details(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			return View();
			//return RedirectToAction("Reviews", new { id = id });
			//return RedirectToAction("Index", "Review", new { restaurantId = id });
		}

		// GET Restaurant/Reviews/5
		// Displays the list of reviews associated with the selected restaurant
		public ActionResult Reviews(int? id, string sortOrder) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			ViewBag.RatingSortParam = String.IsNullOrEmpty(sortOrder) ? "rating" : "rating_desc";
			Restaurant restaurant = db.Restaurants.SingleOrDefault(r => r.RestaurantID == id);

			if (restaurant == null) {
				return HttpNotFound();
			}

			switch (sortOrder) {
				case "rating":
					restaurant.Reviews = restaurant.Reviews.OrderBy(r => r.Rating).ToList();
					break;
				case "rating_desc":
					restaurant.Reviews = restaurant.Reviews.OrderByDescending(r => r.Rating).ToList();
					break;
				default:
					restaurant.Reviews = restaurant.Reviews.OrderBy(r => r.ModifiedDate).ToList();
					break;
			}

			return View(restaurant);
		}

		// GET: Restaurant/Create
		[Authorize(Roles = "admin")]
		public ActionResult Create() {
			return View();
		}

		// POST: Restaurant/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "admin")]
		public ActionResult Create([Bind(Include = "Name,Phone,Street,City,State,Country,PostalCode")] Restaurant restaurant) {
			try {
				if (ModelState.IsValid) {
					db.Restaurants.Add(restaurant);
					db.SaveChanges();
					return RedirectToAction("Index");
				}
			} catch (DataException) {
				ModelState.AddModelError("", "Unable to save changes.");
			}

			return View(restaurant);
		}

		// GET: Restaurant/Edit/5
		[Authorize(Roles = "admin")]
		public ActionResult Edit(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Restaurant restaurant = db.Restaurants.Find(id);
			if (restaurant == null) {
				return HttpNotFound();
			}
			return View(restaurant);
		}

		// POST: Restaurant/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "admin")]
		public ActionResult Edit([Bind(Include = "RestaurantID,Name,Phone,Street,City,State,Country,PostalCode")] Restaurant restaurant) {

			
			if (ModelState.IsValid) {
				db.Entry(restaurant).State = EntityState.Modified;
				db.SaveChanges();
				return View("Index");
			}
				
			return View(restaurant);
		}

		// GET: Restaurant/Delete/5
		[Authorize(Roles = "admin")]
		public ActionResult Delete(int? id, bool? saveChangesError=false) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			if (saveChangesError.GetValueOrDefault()) {
				ViewBag.ErrorMessage = "Delete failed.";
			}
			Restaurant restaurant = db.Restaurants.Find(id);
			if (restaurant == null) {
				return HttpNotFound();
			}
			return View(restaurant);
		}

		// POST: Restaurant/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "admin")]
		public ActionResult Delete(int id) {
			try {
				Restaurant restaurant = db.Restaurants.Find(id);
				db.Reviews.RemoveRange(restaurant.Reviews);
				db.Restaurants.Remove(restaurant);
				db.SaveChanges();
			} catch (DataException) {
				return RedirectToAction("Delete", new { id = id, saveChangesError = false });
			}
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing) {
			if (disposing) {
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

Roasts-and-Rants/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Roasts_and_Rants.DAL;
using Roasts_and_Rants.Models;

namespace Roasts_and_Rants.Controllers {

	public class ReviewController : Controller {

		private RestaurantReviewContext db = new RestaurantReviewContext();
		private ApplicationDbContext context = new ApplicationDbContext();

		// Receives id from RestaurantController
		// GET: Review/id
		public ActionResult Index(string sortOrder) {
			
			ViewBag.NameSortParam = sortOrder == "name_desc" ? "name" : "name_desc";
			ViewBag.RatingSortParam = sortOrder == "rating" ? "rating_desc" : "rating";
			var reviews = from r in db.Reviews
							  select r;

			switch (sortOrder) {
				case "name":
					reviews = reviews.OrderBy(r => r.Restaurant.Name);
					break;
				case "name_desc":
					reviews = reviews.OrderByDescending(r => r.Restaurant.Name);
					break;
				case "rating":
					reviews = reviews.OrderBy(r => r.Rating);
					break;
				case "rating_desc":
					reviews = reviews.OrderByDescending(r => r.Rating);
					break;
				default:
					reviews = reviews.OrderBy(r => r.ModifiedDate);
					break;
			}

			return View(reviews);
		}

		// Currently, not in use
		// GET: Review/Details/5
		public ActionResult Details(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Review review = db.Reviews.Find(id);
			if (review == null) {
				return HttpNotFound();
			}
			return View(review);
		}

		// GET: Review/Create
		[Authorize]
		public ActionResult Create(int restaurantID) {
			ViewBag.CurrentRestaurant = restaurantID;
			ViewBag.CurrentUser = User.Identity.GetUserId();
			return View();
		}

		// POST: Review/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[Authorize]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "RestaurantId,Rating,Content,Anonymous")] Review review) {
			review.UserID = User.Identity.GetUserId();
			review.UserName = User.Identity.GetUserName();
			review.ModifiedDate = DateTime.Now;

			if (ModelState.IsValid) {
				db.Reviews.Add(review);
				db.SaveChanges();
				return RedirectToAction("Reviews", "Restaurant", new { id = review.RestaurantID });
			}

			return View(review);
		}

		// GET: Review/Edit/5
		public ActionResult Edit(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			if (User.Identity.GetUserId() == null) {
				return RedirectToAction("Login", "Account");
			}

			Review review = db.Reviews.Find(id);
			if (review == null) {
				return HttpNotFound();
			}
			
			return View(review);
		}

		// POST: Review/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "ReviewID,Rating,Content,RestaurantID,UserName")] Review review) {

			review.ModifiedDate = DateTime.Now;
			if (ModelState.IsValid) {
				db.Entry(review).State = EntityState.Modified;

				db.SaveChanges();
				return RedirectToAction("Index", new { id = review.RestaurantID });
			}
			return View("Index", new { id = review.RestaurantID });
		}

		// GET: Review/Delete/5
		public ActionResult Delete(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Review review = db.Reviews.Find(id);
			if (review == null) {
				return HttpNotFound();
			}
			return View(review);
		}

		// POST: Review/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id) {
			Review review = db.Reviews.Find(id);
			db.Reviews.Remove(review);
			db.SaveChanges();
			return RedirectToAction("Reviews", "Restaurant", new { review.RestaurantID });
		}

		protected override void Dispose(bool disposing) {
			if (disposing) {
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

Roasts-and-Rants/Views/Restaurant/Create.cshtml
@model Roasts_and_Rants.Models.Restaurant

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Roasts-and-Rants/Views/Restaurant/Delete.cshtml
@model Roasts_and_Rants.Models.Restaurant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Roasts-and-Rants/Views/Restaurant/Details.cshtml
@model Roasts_and_Rants.Models.Restaurant

@{
	ViewBag.Title = "Reviews";
}

<h2>Reviews for @Model.Name</h2>

<p>
	@Html.ActionLink("Add a review", "Review", "Create", new { id = Model.RestaurantID, username = HttpContext.Current.User.Identity.Name }, null)
</p>

<div>
	<table class="table">
		<tr>
			<th>User</th>
			<th>Rating</th>
			<th>Comment</th>
			<th>Last Modified Date</th>
		</tr>
		@foreach (var item in Model.Reviews) {
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.UserName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Rating)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Content)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ModifiedDate)
				</td>
				<td>
					@if (HttpContext.Current.User.Identity.Name == item.UserName) {
						@Html.ActionLink("Edit", "Edit", "Review", new { id = item.ReviewID }, null)
						@: |
						@Html.ActionLink("Delete", "Delete", "Review", new { id = item.ReviewID }, null)
					}
				</td>
			</tr>
		}
	</table>
</div>
<p>
	@Html.ActionLink("Back to Restaurants", "Index", "Restaurant")
</p>

Roasts-and-Rants/Views/Restaurant/Edit.cshtml
@model Roasts_and_Rants.Models.Restaurant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
		@Html.HiddenFor(model => model.RestaurantID)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Roasts-and-Rants/Views/Restaurant/Index.cshtml
@model IEnumerable<Roasts_and_Rants.Models.Restaurant>

@{
    ViewBag.Title = "Index";
}

<h2>Restaurants</h2>

@using (Html.BeginForm()) {
	<p>
		Find by name, address, or phone @Html.TextBox("SearchString")
		<input type="submit" value="Search" />
	</p>
}

<p>
	@Html.ActionLink("Add a new restaurant", "Create")
</p>
<table class="table">
    <tr>
        <th>
			@Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParam })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
		<th>
			@Html.DisplayName("Address")
		</th>
		<th>
			@Html.ActionLink("Average Rating", "Index", new { sortOrder = ViewBag.RatingSortParam })
		</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Street) <br />
			@Html.DisplayFor(modelItem => item.City), @Html.DisplayFor(modelItem => item.State), @Html.DisplayFor(modelItem => item.Country) @Html.DisplayFor(modelItem => item.PostalCode)
        </td>
		<td>
			@Html.DisplayFor(modelItem => item.AverageRating)
			(@item.Reviews.Count @{ViewBag.ReviewMessage = (item.Reviews.Count == 1 ? "review" : "reviews");} @ViewBag.ReviewMessage)
		</td>
		<td>
			@Html.ActionLink("Reviews", "Reviews", "Restaurant", new { id = item.RestaurantID }, null)
			@if (HttpContext.Current.User.IsInRole("admin")) {
				@: | 
				@Html.ActionLink("Edit", "Edit", new { id = item.RestaurantID });
				@:|
				@Html.ActionLink("Delete", "Delete", new { id = item.RestaurantID });
			}
		</td>
    </tr>
}

</table>

Roasts-and-Rants/Views/Restaurant/Reviews.cshtml
@model Roasts_and_Rants.Models.Restaurant

@{
	ViewBag.Title = "Reviews";
}

<h2>Reviews for @Model.Name</h2>

<p>
	@Html.ActionLink("Add a review", "Create", "Review", new { RestaurantID = Model.RestaurantID }, null)
</p>

<div>
	<table class="table">
		<tr>
			<th>User</th>
			<th>@Html.ActionLink("Rating", "Reviews", new { id = Model.RestaurantID, sortOrder = ViewBag.RatingSortParam })</th>
			<th>Comment</th>
		</tr>
		@foreach (var item in Model.Reviews) {
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.UserName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Rating)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Content)
				</td>
				<td>
					@if (HttpContext.Current.User.Identity.Name == item.UserName) {
						@Html.ActionLink("Edit", "Edit", "Review", new { id = item.ReviewID }, null)
						@: |
						@Html.ActionLink("Delete", "Delete", "Review", new { id = item.ReviewID, restaurantID = item.RestaurantID }, null)
					}
				</td>
			</tr>
		}
	</table>
</div>
<p>
	@Html.ActionLink("Back to Restaurants", "Index", "Restaurant")
</p>